# Generated by Django 5.2.5 on 2025-08-09 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='post',
            table='Все посты',
        ),
    ]
